# 오류 처리

오류 처리는 앱이라면 디바이스의 실패, 사용자의 입력 이상 문제 등을 고려하더라도 반드시 필요ㅏㄴ 요소 중 하나이다. 이러한 책임을 바로 잡아야하는 건 결국 프로그래머에게 돌아간다.


우리 프로그래머들은 이러한 오류 처리에 상당수의 코드를 작성하는데 이 코드들이 흩어져있고 더러워진다면 추후 실제 코드를 파악하는 일은 너무 어려울 것이다. 
결국 우리는 이러한 오류 처리 코드들도 깔끔하게 작성해야 한다.

그렇게 하기 위해서 책에서는 다음의 방식들을 제시하고 있다.

## 예외의 사용

예전에는 예외를 지원해주지 않았다. 즉, 과거의 코드는 다음과 같다.

<pre><code>
public class DeviceController {
    ...
    public void sendShutDown() {
        DeviceHandle handle = getHandle(DEV1);

        if (handle != DeviceHandle.INVALID) {
            retrieveDEviceRecord(handle);
            
            // 디바이스가 일시정지 상태가 아니라면 종료한다.
            if (recored.getStatus() != DEVICE_SUSPENDED) {
                pauseDevice(handle);
                clearDeviceWorkQueue(handle);
    
                closeDevice(handle);
            } else {
                logger.log("Device suspended. Unable to shut down");
            }
        } else {
            logger.log("Invalid handle for: " + DEV1.toString());
        }
    }
}
</code></pre>


위의 코드의 경우 **DEVICE_SUSPENDED**라는 오류 플래그를 설정하거나 **DeviceHandle.INVALID** 처럼 오류 코드를 반환 받아 분기 처리를 통해 로직을 구현한 코드이다. 이러한 코드는 결국 호출자 코드가 복잡해지며 함수 호출 즉시 오류를 확인해야하는데 이 단계를 꼼꼼히 기억하고 처리하는 것은 어렵다.

다음은 예외를 던져 처리하는 코드이다.


<pre><code>

public class DeviceController {
    ...

    public void sendShutDown() {
        try {
            tryToShutDown();
        } catch (DeviceShutDownError e) {
            logger.log(e);
        }
    }

    private void tryToShutDown() throws DeviceShutDownError {
        DeviceHandle handle = getHandle(DEV1);
        DeviceRecored record = retrieveDeviceRecord(handle);

        pauseDevice(handle);
        clearDeviceWorkQueue(handle);
        cloaseDevice(handle);
    }

    private DeviceHandle getHandle(DeviceID id) {
        ...
        throw new DeviceShutDownError("Invalid handle for: " + id.toString());
        ...
    }

    ...
}

</code></pre>

위 코드는 디바이스를 종료하는 알고리즘과 오류 코드를 처리하는 알고리즘이 분리되어 있는 것을 확인할 수 있어 추후 코드를 확인하고 이해하는데에 큰 무리가 없다.

## Try-Catch-Finally 문 사용

즉, 예외 코드를 적절히 사용하자.
그 중 Try-Catch-Finally는 범위를 정의하여 로직을 구현할 수 있다.

> DB를 살펴 볼 때 하나의 트랜잭션 단위라고 보면 편하다!

다음의 코드들을 하나씩 살펴보자.

<pre><code>
<1>
public List<RecordedGrip> retrieveSection(String sectionName) {
    return new ArrayList<RecorededGrip> ();
}

<2>
public List<RecordedGrip> retrieveSection(String sectionName) {
    try {
        FileINputStream stream = new FileInputStream(sectionName)
    } catch (Exception e) {
        throw new StorageException("retrieval error", e);
    }

    return new ArrayList<RecorededGrip>();
}

<3>
public List<RecorededGrip> retrieveSection(String sectionName) {
    try {
        FileINputStream stream = new FileInputStream(sectionName);
        stream.close();
    } catch (FileNotFOundException e) {
        throw new StorageException("retrieval error", e);
    }

    return new ArrayList<RecordedGrip>();
}
</code></pre>

- <1> : 코드가 예외를 던지지 않는다.
- <2> : 코드가 예외를 던지지만 예외 유형을 좀 더 좁히도록 리팩토링이 가능한다.
- <3> : 실제 catch 블록에서 예외 유형을 좁협 FileInputStream 생성자가 던지는 FileNoutFOundException을 잡아낸다.


## 미확인 예외의 사용

이전에는 학인된 예외와 미확인 예외에서의 논쟁이 존재했지만 현재는 미확인 예외를 권하는 편이다.

그 이유로는 확인된 예외는 OCP(Open Closed Principle)을 위반한다.

함수 내부에 여러 함수가 존재한다고 보자.

계속 아래 함수를 호출하며 단계가 내려가는데 이 과정에서 최하위 함수를 변경해 새로운 오류를 던진다고 생각해보면 최하위 함수에 새로운 throw를 추가해야한다.

그러면 변경한 함수를 호출하는 함수 모두가 예외처리(1. catch 블록에서의 새로운 예외처리, 2. 선언부에 Throw절 추가)를 해야한다.

즉, 최하위 단계에서 최상위 단계까지의 연쇄적인 수정의 문젱다. 또, throw 경로에 위치하는 모든 함수는 최하위 단계에서 던지는 예외를 알아야 하므로 캡슐화가 깨진다.

> 때로 아주 중요한 라이브러리 작성 시 모든 예외를 잡아야하지만 그러한 의존성의 비용이 이익보다 크기에 이런 비용적인 측면을 고려해서 결정해야 한다.


## 예외에 의미를 제공해라

자바에서 모든 예외에 호출 스택을 제공하지만 그거만으로 코드의 의도를 파악하고 오류를 확인하기는 어렵다. 그렇기에 예외르 던질 때 **전후 상황**을 충분히 덧붙이고 정보를 던져야한다. 다음과 같은 정보가 제공될 수 있다.

- 실패한 연산 이름
- 실패 유형
- 로깅

## 호출자를 고려해 예외 클래스를 정의

오류를 분류하는 방법은 다양하다. 그렇기에 호출자를 고려해 예외 클래스를 정의하는 것이 매우 중요하다. 그러기 위해서 프로그래머들은 애플리케이션에서 오류를 잘 정의해아한다.

즉, **오류를 잡아내는 방법**에 큰 관심사를 두어야 한다.

다음은 외부 라이브러리를 호출하는 try-catch-finally 문을 포함한 코드이다.

<pre><code>
ACMEPort port = new ACMEPort(12);

try {
    port.open();
} catch (DeviceResponseException e) {
    reportPortError(e);
    logger.log("Device response exception", e);
} catch (ACM1212UnlockedException e) {
    reportPortError(e);
    logger.log("Unlock exception", e); 
} catch (GMXError e) {
    reportPortError(e);
    logger.log("Device response exception"); 
} finally {
    ....
}
</code></pre>

코드의 중복이 있으며 예외 유형과 무관하게 예외에 대응하는 방식이 동일하다. 이러한 코드는 호출하는 라이브러리 API를 감싸면서 예외 유형 하나를 반환하는 방식으로 깔끔하게 수정할 수 있다.<br>
그렇게 하기 위해서 Wrapper 클래스인 LocalPort 클래스를 통해 ACMEPort 클래스가 던지는 예외를 잡아 변환하도록 한다.

<pre><code>
<1> : Wrapper Class LocalPort
public class LocalPort {
    private ACMEPort innerPort;

    public LocalPort(int portNumber) {
        innerPOrt = new ACMEPort(portNumber);
    }

    public void open() {
        try {
            innerPOrt.open();
        } catch (DeviceResponseException e) {
            reportPortError(e);
            logger.log("Device response exception", e);
        } catch (ACM1212UnlockedException e) {
            reportPortError(e);
            logger.log("Unlock exception", e); 
        } catch (GMXError e) {
            reportPortError(e);
            logger.log("Device response exception"); 
        } finally {
            ....
        }
    }
}


<2> Clean Code
LocalPort port = new LocalPort(12);
try {
    port.open();
} catch (PortDeviceFailure e) {
    reportError(e);
    logger.log(e.getMessage(), e);
} finally {
    ...
}
</code></pre>

외부 라이브러리를 사용 시에 감싸기 기법을 사용하면 다음과 같은 장점을 취할 수 있다.

- 외부라이브러리와 프로그램 사이의 의존성 최소화
- 특정 업체의 설계방식에 구애 x

## 정상 흐름의 정의

책에서 보았을 때 말이 조금 어려웠는데 예제를 우선 살펴 보면 어느정도 이해가 편하다.

<pre><code>
try {
    MealExpenses expenses = expenseReportDAO.getMeals(employee.getID());
    m_total += expenses.getTotal();
} catch(MealExpensesNotFound e) {
    m_total += getMealPerDiem();
}
</code></pre>


**try :**  식비를 비용으로 청구 시 청구한 식비를 총계에 더한다.
**catch :** 청구하지 않은 경우 일일 기본 식비를 총계에 더한다.

이러한 부분을 좀 더 간결하게 작성할 수 있다.

<pre><code>
<1> MealExpenses 추상화
public class PerDiemMealExpenses implements MealExpenses {
    public int getTotal() {
        // 기본 값으로 일일 기본 식비 반환
    }
}

<2>
PerDiemMealExpenses expenses = expenseReportDAO.getMeals(employee.getID());
m_total += expenses
</code></pre>

이러한 식으로 좀 더 코드를 간결하게 이어갈 수 있다.


> **특수 사례 패턴** <br> 클래스를 만들거나 객체를 조작해 특수 사례를 처리하는 방식이다. 이렇게 하여 클래스나 객체가 예외저깅ㄴ 상황을 캡슐화 처리하도록 하여 클라이언트 코드가 예외적인 상황을 처리할 필요가 없어진다.

## null 금지

null의 사용은 오류를 헷갈리게 하기에 다음과 같이 사용되는 사례들을 금한다.

### null 반환

null을 반환하는 코드는 호출자 함수에게 일거리를 늘리고 본인의 문제를 떠넘기는 행위이다.
null을 반환하고 싶은 경우 예외를 던지거나 특수 사례 객체를 사용하기를 바란다.

<pre><code>
<1> null 반환 코드
List<Employee> employees = getEmployees();
if (employees != null) {
    for(Employee e : employees) {
        totalPay += e.getPay();
    }
}

<2> 빈 리스트 반환 코드
List<Employee> employees = getEmployees();
for(Employee e : employees) {
    totalPay += e.getPay();
}

<3> Java의 Collections.emptyList() 사용 클래스
public List<Employee> getEmployees() {
    if (직원 X) {
        return Collections.emptyList();
    }
}
</code></pre>

### null 전달

정상적인 인수로 null을 기대하지 않는다면 메서드로 null을 전달하는 코드는 최대한 피한다.

<pre><code>
<1> null 반환
public class MetricsCalculator {
    public double xProjection(Point p1, Point p2) {
        return (p2.x - p1.x) *1.5;
    }
    ...
}

calculator.xProjection(null, new Point(12, 13)); -> NullPointerException

<2> 새로운 예외 유형을 생성
public class MetricsCalculator {
    public double xProjection(Point p1, point p2) {
        if (p1 == null || p2 == null) {
            throw InvalidArgumentException("Invalid argument for MetricsCalculator.xProjection");
        }

        return (p2.x - p1.x) * 1.5;
    }
}

<3> In Java, assert tkdyd cjfl
public class MetricsCalculator {
    public double xProjection(Point p1, Point p2) {
        assert p1 != null : "p1 should not be null";
        assert p2 != null : "p2 should not be null";
        return (p2.x - p1.x) * 1.5;
    }
}

</code></pre>


null들은 적절히 처리하는 방법이 없기에 애초에 null을 넘기지 못하도록 금지하는 것이 합리적이다.